/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanosEPrecosRouteImport } from './routes/planos-e-precos'
import { Route as ParaParceirosRouteImport } from './routes/para-parceiros'
import { Route as ParaEmpresasRouteImport } from './routes/para-empresas'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated/pro'
import { Route as AuthenticatedOnboardingProRouteImport } from './routes/_authenticated/onboarding-pro'
import { Route as AuthenticatedOnboardingEmpresaRouteImport } from './routes/_authenticated/onboarding-empresa'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProIndexRouteImport } from './routes/_authenticated/pro.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedProServicosRouteImport } from './routes/_authenticated/pro.servicos'
import { Route as AuthenticatedProPacientesRouteImport } from './routes/_authenticated/pro.pacientes'
import { Route as AuthenticatedProOrcamentosRouteImport } from './routes/_authenticated/pro.orcamentos'
import { Route as AuthenticatedProNotificacoesRouteImport } from './routes/_authenticated/pro.notificacoes'
import { Route as AuthenticatedProImpulsionarRouteImport } from './routes/_authenticated/pro.impulsionar'
import { Route as AuthenticatedProFinanceiroRouteImport } from './routes/_authenticated/pro.financeiro'
import { Route as AuthenticatedProCrmRouteImport } from './routes/_authenticated/pro.crm'
import { Route as AuthenticatedProAgendaRouteImport } from './routes/_authenticated/pro.agenda'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppOrcamentosRouteImport } from './routes/_authenticated/app.orcamentos'
import { Route as AuthenticatedAppMensagensRouteImport } from './routes/_authenticated/app.mensagens'
import { Route as AuthenticatedAppFavoritosRouteImport } from './routes/_authenticated/app.favoritos'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app.documentos'
import { Route as AuthenticatedAppConsultasRouteImport } from './routes/_authenticated/app.consultas'
import { Route as AuthenticatedAppCarteiraRouteImport } from './routes/_authenticated/app.carteira'
import { Route as AuthenticatedAppBuscarRouteImport } from './routes/_authenticated/app.buscar'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments.webhook'
import { Route as ApiPublicAutomationRunRouteImport } from './routes/api/public/automation.run'
import { Route as AuthenticatedProOrcamentosIdRouteImport } from './routes/_authenticated/pro.orcamentos.$id'
import { Route as AuthenticatedProCrmIdRouteImport } from './routes/_authenticated/pro.crm.$id'
import { Route as AuthenticatedAppProfissionalIdRouteImport } from './routes/_authenticated/app.profissional.$id'
import { Route as AuthenticatedAppOrcamentosIdRouteImport } from './routes/_authenticated/app.orcamentos.$id'
import { Route as AuthenticatedAppEmpresaIdRouteImport } from './routes/_authenticated/app.empresa.$id'
import { Route as AuthenticatedAppCheckoutIdRouteImport } from './routes/_authenticated/app.checkout.$id'
import { Route as AuthenticatedAppChatIdRouteImport } from './routes/_authenticated/app.chat.$id'

const PlanosEPrecosRoute = PlanosEPrecosRouteImport.update({
  id: '/planos-e-precos',
  path: '/planos-e-precos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaParceirosRoute = ParaParceirosRouteImport.update({
  id: '/para-parceiros',
  path: '/para-parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEmpresasRoute = ParaEmpresasRouteImport.update({
  id: '/para-empresas',
  path: '/para-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingProRoute =
  AuthenticatedOnboardingProRouteImport.update({
    id: '/onboarding-pro',
    path: '/onboarding-pro',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingEmpresaRoute =
  AuthenticatedOnboardingEmpresaRouteImport.update({
    id: '/onboarding-empresa',
    path: '/onboarding-empresa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProIndexRoute = AuthenticatedProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedProServicosRoute =
  AuthenticatedProServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProPacientesRoute =
  AuthenticatedProPacientesRouteImport.update({
    id: '/pacientes',
    path: '/pacientes',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProOrcamentosRoute =
  AuthenticatedProOrcamentosRouteImport.update({
    id: '/orcamentos',
    path: '/orcamentos',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProNotificacoesRoute =
  AuthenticatedProNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProImpulsionarRoute =
  AuthenticatedProImpulsionarRouteImport.update({
    id: '/impulsionar',
    path: '/impulsionar',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProFinanceiroRoute =
  AuthenticatedProFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProCrmRoute = AuthenticatedProCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProAgendaRoute = AuthenticatedProAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrcamentosRoute =
  AuthenticatedAppOrcamentosRouteImport.update({
    id: '/orcamentos',
    path: '/orcamentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMensagensRoute =
  AuthenticatedAppMensagensRouteImport.update({
    id: '/mensagens',
    path: '/mensagens',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFavoritosRoute =
  AuthenticatedAppFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConsultasRoute =
  AuthenticatedAppConsultasRouteImport.update({
    id: '/consultas',
    path: '/consultas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCarteiraRoute =
  AuthenticatedAppCarteiraRouteImport.update({
    id: '/carteira',
    path: '/carteira',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBuscarRoute = AuthenticatedAppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationRunRoute = ApiPublicAutomationRunRouteImport.update({
  id: '/api/public/automation/run',
  path: '/api/public/automation/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProOrcamentosIdRoute =
  AuthenticatedProOrcamentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProOrcamentosRoute,
  } as any)
const AuthenticatedProCrmIdRoute = AuthenticatedProCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProCrmRoute,
} as any)
const AuthenticatedAppProfissionalIdRoute =
  AuthenticatedAppProfissionalIdRouteImport.update({
    id: '/profissional/$id',
    path: '/profissional/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOrcamentosIdRoute =
  AuthenticatedAppOrcamentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppOrcamentosRoute,
  } as any)
const AuthenticatedAppEmpresaIdRoute =
  AuthenticatedAppEmpresaIdRouteImport.update({
    id: '/empresa/$id',
    path: '/empresa/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCheckoutIdRoute =
  AuthenticatedAppCheckoutIdRouteImport.update({
    id: '/checkout/$id',
    path: '/checkout/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatIdRoute = AuthenticatedAppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/para-empresas': typeof ParaEmpresasRoute
  '/para-parceiros': typeof ParaParceirosRoute
  '/planos-e-precos': typeof PlanosEPrecosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding-empresa': typeof AuthenticatedOnboardingEmpresaRoute
  '/onboarding-pro': typeof AuthenticatedOnboardingProRoute
  '/pro': typeof AuthenticatedProRouteWithChildren
  '/pay/$token': typeof PayTokenRoute
  '/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/app/carteira': typeof AuthenticatedAppCarteiraRoute
  '/app/consultas': typeof AuthenticatedAppConsultasRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/app/orcamentos': typeof AuthenticatedAppOrcamentosRouteWithChildren
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/pro/agenda': typeof AuthenticatedProAgendaRoute
  '/pro/crm': typeof AuthenticatedProCrmRouteWithChildren
  '/pro/financeiro': typeof AuthenticatedProFinanceiroRoute
  '/pro/impulsionar': typeof AuthenticatedProImpulsionarRoute
  '/pro/notificacoes': typeof AuthenticatedProNotificacoesRoute
  '/pro/orcamentos': typeof AuthenticatedProOrcamentosRouteWithChildren
  '/pro/pacientes': typeof AuthenticatedProPacientesRoute
  '/pro/servicos': typeof AuthenticatedProServicosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/pro/': typeof AuthenticatedProIndexRoute
  '/app/chat/$id': typeof AuthenticatedAppChatIdRoute
  '/app/checkout/$id': typeof AuthenticatedAppCheckoutIdRoute
  '/app/empresa/$id': typeof AuthenticatedAppEmpresaIdRoute
  '/app/orcamentos/$id': typeof AuthenticatedAppOrcamentosIdRoute
  '/app/profissional/$id': typeof AuthenticatedAppProfissionalIdRoute
  '/pro/crm/$id': typeof AuthenticatedProCrmIdRoute
  '/pro/orcamentos/$id': typeof AuthenticatedProOrcamentosIdRoute
  '/api/public/automation/run': typeof ApiPublicAutomationRunRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/para-empresas': typeof ParaEmpresasRoute
  '/para-parceiros': typeof ParaParceirosRoute
  '/planos-e-precos': typeof PlanosEPrecosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding-empresa': typeof AuthenticatedOnboardingEmpresaRoute
  '/onboarding-pro': typeof AuthenticatedOnboardingProRoute
  '/pay/$token': typeof PayTokenRoute
  '/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/app/carteira': typeof AuthenticatedAppCarteiraRoute
  '/app/consultas': typeof AuthenticatedAppConsultasRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/app/orcamentos': typeof AuthenticatedAppOrcamentosRouteWithChildren
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/pro/agenda': typeof AuthenticatedProAgendaRoute
  '/pro/crm': typeof AuthenticatedProCrmRouteWithChildren
  '/pro/financeiro': typeof AuthenticatedProFinanceiroRoute
  '/pro/impulsionar': typeof AuthenticatedProImpulsionarRoute
  '/pro/notificacoes': typeof AuthenticatedProNotificacoesRoute
  '/pro/orcamentos': typeof AuthenticatedProOrcamentosRouteWithChildren
  '/pro/pacientes': typeof AuthenticatedProPacientesRoute
  '/pro/servicos': typeof AuthenticatedProServicosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/pro': typeof AuthenticatedProIndexRoute
  '/app/chat/$id': typeof AuthenticatedAppChatIdRoute
  '/app/checkout/$id': typeof AuthenticatedAppCheckoutIdRoute
  '/app/empresa/$id': typeof AuthenticatedAppEmpresaIdRoute
  '/app/orcamentos/$id': typeof AuthenticatedAppOrcamentosIdRoute
  '/app/profissional/$id': typeof AuthenticatedAppProfissionalIdRoute
  '/pro/crm/$id': typeof AuthenticatedProCrmIdRoute
  '/pro/orcamentos/$id': typeof AuthenticatedProOrcamentosIdRoute
  '/api/public/automation/run': typeof ApiPublicAutomationRunRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/para-empresas': typeof ParaEmpresasRoute
  '/para-parceiros': typeof ParaParceirosRoute
  '/planos-e-precos': typeof PlanosEPrecosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding-empresa': typeof AuthenticatedOnboardingEmpresaRoute
  '/_authenticated/onboarding-pro': typeof AuthenticatedOnboardingProRoute
  '/_authenticated/pro': typeof AuthenticatedProRouteWithChildren
  '/pay/$token': typeof PayTokenRoute
  '/_authenticated/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/_authenticated/app/carteira': typeof AuthenticatedAppCarteiraRoute
  '/_authenticated/app/consultas': typeof AuthenticatedAppConsultasRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/_authenticated/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/_authenticated/app/orcamentos': typeof AuthenticatedAppOrcamentosRouteWithChildren
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/pro/agenda': typeof AuthenticatedProAgendaRoute
  '/_authenticated/pro/crm': typeof AuthenticatedProCrmRouteWithChildren
  '/_authenticated/pro/financeiro': typeof AuthenticatedProFinanceiroRoute
  '/_authenticated/pro/impulsionar': typeof AuthenticatedProImpulsionarRoute
  '/_authenticated/pro/notificacoes': typeof AuthenticatedProNotificacoesRoute
  '/_authenticated/pro/orcamentos': typeof AuthenticatedProOrcamentosRouteWithChildren
  '/_authenticated/pro/pacientes': typeof AuthenticatedProPacientesRoute
  '/_authenticated/pro/servicos': typeof AuthenticatedProServicosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/pro/': typeof AuthenticatedProIndexRoute
  '/_authenticated/app/chat/$id': typeof AuthenticatedAppChatIdRoute
  '/_authenticated/app/checkout/$id': typeof AuthenticatedAppCheckoutIdRoute
  '/_authenticated/app/empresa/$id': typeof AuthenticatedAppEmpresaIdRoute
  '/_authenticated/app/orcamentos/$id': typeof AuthenticatedAppOrcamentosIdRoute
  '/_authenticated/app/profissional/$id': typeof AuthenticatedAppProfissionalIdRoute
  '/_authenticated/pro/crm/$id': typeof AuthenticatedProCrmIdRoute
  '/_authenticated/pro/orcamentos/$id': typeof AuthenticatedProOrcamentosIdRoute
  '/api/public/automation/run': typeof ApiPublicAutomationRunRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/para-empresas'
    | '/para-parceiros'
    | '/planos-e-precos'
    | '/admin'
    | '/app'
    | '/onboarding-empresa'
    | '/onboarding-pro'
    | '/pro'
    | '/pay/$token'
    | '/app/buscar'
    | '/app/carteira'
    | '/app/consultas'
    | '/app/documentos'
    | '/app/favoritos'
    | '/app/mensagens'
    | '/app/orcamentos'
    | '/app/perfil'
    | '/pro/agenda'
    | '/pro/crm'
    | '/pro/financeiro'
    | '/pro/impulsionar'
    | '/pro/notificacoes'
    | '/pro/orcamentos'
    | '/pro/pacientes'
    | '/pro/servicos'
    | '/app/'
    | '/pro/'
    | '/app/chat/$id'
    | '/app/checkout/$id'
    | '/app/empresa/$id'
    | '/app/orcamentos/$id'
    | '/app/profissional/$id'
    | '/pro/crm/$id'
    | '/pro/orcamentos/$id'
    | '/api/public/automation/run'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/para-empresas'
    | '/para-parceiros'
    | '/planos-e-precos'
    | '/admin'
    | '/onboarding-empresa'
    | '/onboarding-pro'
    | '/pay/$token'
    | '/app/buscar'
    | '/app/carteira'
    | '/app/consultas'
    | '/app/documentos'
    | '/app/favoritos'
    | '/app/mensagens'
    | '/app/orcamentos'
    | '/app/perfil'
    | '/pro/agenda'
    | '/pro/crm'
    | '/pro/financeiro'
    | '/pro/impulsionar'
    | '/pro/notificacoes'
    | '/pro/orcamentos'
    | '/pro/pacientes'
    | '/pro/servicos'
    | '/app'
    | '/pro'
    | '/app/chat/$id'
    | '/app/checkout/$id'
    | '/app/empresa/$id'
    | '/app/orcamentos/$id'
    | '/app/profissional/$id'
    | '/pro/crm/$id'
    | '/pro/orcamentos/$id'
    | '/api/public/automation/run'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/como-funciona'
    | '/para-empresas'
    | '/para-parceiros'
    | '/planos-e-precos'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/onboarding-empresa'
    | '/_authenticated/onboarding-pro'
    | '/_authenticated/pro'
    | '/pay/$token'
    | '/_authenticated/app/buscar'
    | '/_authenticated/app/carteira'
    | '/_authenticated/app/consultas'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/favoritos'
    | '/_authenticated/app/mensagens'
    | '/_authenticated/app/orcamentos'
    | '/_authenticated/app/perfil'
    | '/_authenticated/pro/agenda'
    | '/_authenticated/pro/crm'
    | '/_authenticated/pro/financeiro'
    | '/_authenticated/pro/impulsionar'
    | '/_authenticated/pro/notificacoes'
    | '/_authenticated/pro/orcamentos'
    | '/_authenticated/pro/pacientes'
    | '/_authenticated/pro/servicos'
    | '/_authenticated/app/'
    | '/_authenticated/pro/'
    | '/_authenticated/app/chat/$id'
    | '/_authenticated/app/checkout/$id'
    | '/_authenticated/app/empresa/$id'
    | '/_authenticated/app/orcamentos/$id'
    | '/_authenticated/app/profissional/$id'
    | '/_authenticated/pro/crm/$id'
    | '/_authenticated/pro/orcamentos/$id'
    | '/api/public/automation/run'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ParaEmpresasRoute: typeof ParaEmpresasRoute
  ParaParceirosRoute: typeof ParaParceirosRoute
  PlanosEPrecosRoute: typeof PlanosEPrecosRoute
  PayTokenRoute: typeof PayTokenRoute
  ApiPublicAutomationRunRoute: typeof ApiPublicAutomationRunRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planos-e-precos': {
      id: '/planos-e-precos'
      path: '/planos-e-precos'
      fullPath: '/planos-e-precos'
      preLoaderRoute: typeof PlanosEPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-parceiros': {
      id: '/para-parceiros'
      path: '/para-parceiros'
      fullPath: '/para-parceiros'
      preLoaderRoute: typeof ParaParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-empresas': {
      id: '/para-empresas'
      path: '/para-empresas'
      fullPath: '/para-empresas'
      preLoaderRoute: typeof ParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding-pro': {
      id: '/_authenticated/onboarding-pro'
      path: '/onboarding-pro'
      fullPath: '/onboarding-pro'
      preLoaderRoute: typeof AuthenticatedOnboardingProRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding-empresa': {
      id: '/_authenticated/onboarding-empresa'
      path: '/onboarding-empresa'
      fullPath: '/onboarding-empresa'
      preLoaderRoute: typeof AuthenticatedOnboardingEmpresaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pro/': {
      id: '/_authenticated/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof AuthenticatedProIndexRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/pro/servicos': {
      id: '/_authenticated/pro/servicos'
      path: '/servicos'
      fullPath: '/pro/servicos'
      preLoaderRoute: typeof AuthenticatedProServicosRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/pacientes': {
      id: '/_authenticated/pro/pacientes'
      path: '/pacientes'
      fullPath: '/pro/pacientes'
      preLoaderRoute: typeof AuthenticatedProPacientesRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/orcamentos': {
      id: '/_authenticated/pro/orcamentos'
      path: '/orcamentos'
      fullPath: '/pro/orcamentos'
      preLoaderRoute: typeof AuthenticatedProOrcamentosRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/notificacoes': {
      id: '/_authenticated/pro/notificacoes'
      path: '/notificacoes'
      fullPath: '/pro/notificacoes'
      preLoaderRoute: typeof AuthenticatedProNotificacoesRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/impulsionar': {
      id: '/_authenticated/pro/impulsionar'
      path: '/impulsionar'
      fullPath: '/pro/impulsionar'
      preLoaderRoute: typeof AuthenticatedProImpulsionarRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/financeiro': {
      id: '/_authenticated/pro/financeiro'
      path: '/financeiro'
      fullPath: '/pro/financeiro'
      preLoaderRoute: typeof AuthenticatedProFinanceiroRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/crm': {
      id: '/_authenticated/pro/crm'
      path: '/crm'
      fullPath: '/pro/crm'
      preLoaderRoute: typeof AuthenticatedProCrmRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/agenda': {
      id: '/_authenticated/pro/agenda'
      path: '/agenda'
      fullPath: '/pro/agenda'
      preLoaderRoute: typeof AuthenticatedProAgendaRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orcamentos': {
      id: '/_authenticated/app/orcamentos'
      path: '/orcamentos'
      fullPath: '/app/orcamentos'
      preLoaderRoute: typeof AuthenticatedAppOrcamentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mensagens': {
      id: '/_authenticated/app/mensagens'
      path: '/mensagens'
      fullPath: '/app/mensagens'
      preLoaderRoute: typeof AuthenticatedAppMensagensRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/favoritos': {
      id: '/_authenticated/app/favoritos'
      path: '/favoritos'
      fullPath: '/app/favoritos'
      preLoaderRoute: typeof AuthenticatedAppFavoritosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/consultas': {
      id: '/_authenticated/app/consultas'
      path: '/consultas'
      fullPath: '/app/consultas'
      preLoaderRoute: typeof AuthenticatedAppConsultasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/carteira': {
      id: '/_authenticated/app/carteira'
      path: '/carteira'
      fullPath: '/app/carteira'
      preLoaderRoute: typeof AuthenticatedAppCarteiraRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/buscar': {
      id: '/_authenticated/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AuthenticatedAppBuscarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/run': {
      id: '/api/public/automation/run'
      path: '/api/public/automation/run'
      fullPath: '/api/public/automation/run'
      preLoaderRoute: typeof ApiPublicAutomationRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pro/orcamentos/$id': {
      id: '/_authenticated/pro/orcamentos/$id'
      path: '/$id'
      fullPath: '/pro/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedProOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedProOrcamentosRoute
    }
    '/_authenticated/pro/crm/$id': {
      id: '/_authenticated/pro/crm/$id'
      path: '/$id'
      fullPath: '/pro/crm/$id'
      preLoaderRoute: typeof AuthenticatedProCrmIdRouteImport
      parentRoute: typeof AuthenticatedProCrmRoute
    }
    '/_authenticated/app/profissional/$id': {
      id: '/_authenticated/app/profissional/$id'
      path: '/profissional/$id'
      fullPath: '/app/profissional/$id'
      preLoaderRoute: typeof AuthenticatedAppProfissionalIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orcamentos/$id': {
      id: '/_authenticated/app/orcamentos/$id'
      path: '/$id'
      fullPath: '/app/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedAppOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedAppOrcamentosRoute
    }
    '/_authenticated/app/empresa/$id': {
      id: '/_authenticated/app/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/app/empresa/$id'
      preLoaderRoute: typeof AuthenticatedAppEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/checkout/$id': {
      id: '/_authenticated/app/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/app/checkout/$id'
      preLoaderRoute: typeof AuthenticatedAppCheckoutIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/$id': {
      id: '/_authenticated/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AuthenticatedAppChatIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppOrcamentosRouteChildren {
  AuthenticatedAppOrcamentosIdRoute: typeof AuthenticatedAppOrcamentosIdRoute
}

const AuthenticatedAppOrcamentosRouteChildren: AuthenticatedAppOrcamentosRouteChildren =
  {
    AuthenticatedAppOrcamentosIdRoute: AuthenticatedAppOrcamentosIdRoute,
  }

const AuthenticatedAppOrcamentosRouteWithChildren =
  AuthenticatedAppOrcamentosRoute._addFileChildren(
    AuthenticatedAppOrcamentosRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBuscarRoute: typeof AuthenticatedAppBuscarRoute
  AuthenticatedAppCarteiraRoute: typeof AuthenticatedAppCarteiraRoute
  AuthenticatedAppConsultasRoute: typeof AuthenticatedAppConsultasRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppFavoritosRoute: typeof AuthenticatedAppFavoritosRoute
  AuthenticatedAppMensagensRoute: typeof AuthenticatedAppMensagensRoute
  AuthenticatedAppOrcamentosRoute: typeof AuthenticatedAppOrcamentosRouteWithChildren
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppChatIdRoute: typeof AuthenticatedAppChatIdRoute
  AuthenticatedAppCheckoutIdRoute: typeof AuthenticatedAppCheckoutIdRoute
  AuthenticatedAppEmpresaIdRoute: typeof AuthenticatedAppEmpresaIdRoute
  AuthenticatedAppProfissionalIdRoute: typeof AuthenticatedAppProfissionalIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBuscarRoute: AuthenticatedAppBuscarRoute,
  AuthenticatedAppCarteiraRoute: AuthenticatedAppCarteiraRoute,
  AuthenticatedAppConsultasRoute: AuthenticatedAppConsultasRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppFavoritosRoute: AuthenticatedAppFavoritosRoute,
  AuthenticatedAppMensagensRoute: AuthenticatedAppMensagensRoute,
  AuthenticatedAppOrcamentosRoute: AuthenticatedAppOrcamentosRouteWithChildren,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppChatIdRoute: AuthenticatedAppChatIdRoute,
  AuthenticatedAppCheckoutIdRoute: AuthenticatedAppCheckoutIdRoute,
  AuthenticatedAppEmpresaIdRoute: AuthenticatedAppEmpresaIdRoute,
  AuthenticatedAppProfissionalIdRoute: AuthenticatedAppProfissionalIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedProCrmRouteChildren {
  AuthenticatedProCrmIdRoute: typeof AuthenticatedProCrmIdRoute
}

const AuthenticatedProCrmRouteChildren: AuthenticatedProCrmRouteChildren = {
  AuthenticatedProCrmIdRoute: AuthenticatedProCrmIdRoute,
}

const AuthenticatedProCrmRouteWithChildren =
  AuthenticatedProCrmRoute._addFileChildren(AuthenticatedProCrmRouteChildren)

interface AuthenticatedProOrcamentosRouteChildren {
  AuthenticatedProOrcamentosIdRoute: typeof AuthenticatedProOrcamentosIdRoute
}

const AuthenticatedProOrcamentosRouteChildren: AuthenticatedProOrcamentosRouteChildren =
  {
    AuthenticatedProOrcamentosIdRoute: AuthenticatedProOrcamentosIdRoute,
  }

const AuthenticatedProOrcamentosRouteWithChildren =
  AuthenticatedProOrcamentosRoute._addFileChildren(
    AuthenticatedProOrcamentosRouteChildren,
  )

interface AuthenticatedProRouteChildren {
  AuthenticatedProAgendaRoute: typeof AuthenticatedProAgendaRoute
  AuthenticatedProCrmRoute: typeof AuthenticatedProCrmRouteWithChildren
  AuthenticatedProFinanceiroRoute: typeof AuthenticatedProFinanceiroRoute
  AuthenticatedProImpulsionarRoute: typeof AuthenticatedProImpulsionarRoute
  AuthenticatedProNotificacoesRoute: typeof AuthenticatedProNotificacoesRoute
  AuthenticatedProOrcamentosRoute: typeof AuthenticatedProOrcamentosRouteWithChildren
  AuthenticatedProPacientesRoute: typeof AuthenticatedProPacientesRoute
  AuthenticatedProServicosRoute: typeof AuthenticatedProServicosRoute
  AuthenticatedProIndexRoute: typeof AuthenticatedProIndexRoute
}

const AuthenticatedProRouteChildren: AuthenticatedProRouteChildren = {
  AuthenticatedProAgendaRoute: AuthenticatedProAgendaRoute,
  AuthenticatedProCrmRoute: AuthenticatedProCrmRouteWithChildren,
  AuthenticatedProFinanceiroRoute: AuthenticatedProFinanceiroRoute,
  AuthenticatedProImpulsionarRoute: AuthenticatedProImpulsionarRoute,
  AuthenticatedProNotificacoesRoute: AuthenticatedProNotificacoesRoute,
  AuthenticatedProOrcamentosRoute: AuthenticatedProOrcamentosRouteWithChildren,
  AuthenticatedProPacientesRoute: AuthenticatedProPacientesRoute,
  AuthenticatedProServicosRoute: AuthenticatedProServicosRoute,
  AuthenticatedProIndexRoute: AuthenticatedProIndexRoute,
}

const AuthenticatedProRouteWithChildren =
  AuthenticatedProRoute._addFileChildren(AuthenticatedProRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingEmpresaRoute: typeof AuthenticatedOnboardingEmpresaRoute
  AuthenticatedOnboardingProRoute: typeof AuthenticatedOnboardingProRoute
  AuthenticatedProRoute: typeof AuthenticatedProRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingEmpresaRoute: AuthenticatedOnboardingEmpresaRoute,
  AuthenticatedOnboardingProRoute: AuthenticatedOnboardingProRoute,
  AuthenticatedProRoute: AuthenticatedProRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ParaEmpresasRoute: ParaEmpresasRoute,
  ParaParceirosRoute: ParaParceirosRoute,
  PlanosEPrecosRoute: PlanosEPrecosRoute,
  PayTokenRoute: PayTokenRoute,
  ApiPublicAutomationRunRoute: ApiPublicAutomationRunRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
